export const portfolioContent = {
  pt: {
    navbar: {
      links: [
        { href: '#about', label: 'Sobre' },
        { href: '#experience', label: 'Experiência' },
        { href: '#skills', label: 'Skills' },
        { href: '#projects', label: 'Projetos' },
        { href: '#contact', label: 'Contato' },
      ],
      cta: 'Fale comigo',
      languageLabel: 'Idioma',
    },
    hero: {
      badge: 'Disponível para novos projetos',
      title: 'Desenvolvedor Full Stack Sênior',
      subtitle: 'Arquitetura de Software • IA & Produtividade com LLMs',
      experienceLine: '+18 anos construindo sistemas de alta performance',
      resumeButton: 'Baixar Currículo',
      githubButton: 'GitHub',
    },
    about: {
      comment: '// SOBRE MIM',
      headingPrefix: 'Experiência que gera',
      headingHighlight: 'resultados',
      paragraphs: [
        'Desenvolvedor Full Stack Sênior com mais de 18 anos de experiência em sistemas corporativos de alta complexidade, com forte atuação no setor de Saúde & Telemedicina. Especialista no ecossistema .NET (Framework ao .NET 9), com domínio em arquiteturas modernas (Microservices, DDD, CQRS, Hexagonal) e mensageria com RabbitMQ/MassTransit.',
        'Atua com as principais LLMs do mercado (ChatGPT, Claude, GitHub Copilot, Codex, Ollama) como ferramentas de alta produtividade e Engenharia de Prompt aplicada ao desenvolvimento. Autenticação avançada com OAuth 2.0, JWT e Keycloak.',
        'Experiência em Cloud (Azure, AWS, GCP, Oracle Cloud), CI/CD com Azure DevOps / GitHub / Bitbucket, observabilidade com Grafana e Zabbix, e bancos de dados relacionais e NoSQL. Minha abordagem combina visão estratégica de negócio com excelência técnica, sempre buscando soluções escaláveis e alinhadas com os objetivos do produto.',
      ],
      highlights: [
        { title: '18+ Anos', desc: 'Experiência em desenvolvimento' },
        { title: 'Microservices', desc: 'DDD, CQRS, Hexagonal, Clean' },
        { title: 'Liderança Técnica', desc: 'Mentoria e code review' },
        { title: 'Saúde & Telemedicina', desc: '13+ anos no setor hospitalar' },
        { title: 'IA & LLMs', desc: 'Copilot, ChatGPT, Claude, Ollama' },
      ],
    },
    experience: {
      comment: '// TRAJETÓRIA',
      headingPrefix: 'Experiência',
      headingHighlight: 'Profissional',
      description: 'Uma trajetória sólida construindo sistemas de missão crítica em empresas de referência no mercado.',
      items: [
        {
          company: 'Shock Tecnologia Consultoria',
          role: 'Desenvolvedor Full Stack Sênior / Tech Lead',
          period: 'Jan/2026 – Atual',
          location: 'Remoto',
          tasks: [
            'Prestação de serviço para clientes como MatriBank e Matri Precatórios em arquitetura moderna e orientada a microsserviços',
            'MatriBank: APIs .NET Core com OAuth 2.0 e JWT; Azure App Services, Key Vault e Storage; CI/CD no Azure DevOps',
            'Microsserviços com RabbitMQ e MassTransit; PostgreSQL e Redis para estratégias de cache; Docker; GitHub e Bitbucket',
            'Vivência em processos bancários e meios de pagamento (PIX, TED, TEF e Open Finance), com rotinas de extrato e conciliação',
            'Integrações com provedores financeiros como Autbank e Celcoin',
            'Matri Precatórios: soluções em AWS (Lambda, S3, RDS) e GCP; pipelines de automação com Python',
            'Adoção de IA e LLMs (ChatGPT/Codex, Claude, Copilot, Ollama local) com engenharia de prompt para testes, refatoração e documentação',
            'ALM e controle de versão com GitHub, Bitbucket, Azure DevOps e TFS; code review, GitFlow e pipelines CI/CD automatizados',
          ],
        },
        {
          company: 'ITLean Consultoria',
          role: 'Desenvolvedor Full Stack Sênior',
          period: 'Jun/2024 – Jan/2026',
          location: 'Remoto',
          tasks: [
            'Prestação de serviço para clientes como GPA e Care Plus em modernização de sistemas e evolução de plataformas críticas',
            'GPA: manutenção de sistemas de preços e etiquetagem com WebForms (.NET Framework 4.7) e Oracle',
            'Criação de APIs em .NET 6/7/8 com CQRS, Clean Architecture e SOLID, integradas a sistemas legados (mainframe)',
            'Mensageria e processamento assíncrono com MassTransit e RabbitMQ para escalabilidade e resiliência',
            'Otimização de procedures e triggers em Oracle com apoio de LLMs (Claude, GitHub Copilot e Cursor), incluindo criação de agentes',
            'Care Plus: migração de legado Delphi/WebForms para .NET Core com microsserviços, CQRS e mensageria',
            'Desenvolvimento de APIs e interfaces com Angular e React para fluxos de cadastro, adesão e gestão de beneficiários',
            'Automação de testes de código e geração de documentação técnica com LLMs para acelerar entregas e melhorar qualidade',
          ],
        },
        {
          company: 'Amil Assistência Médica Internacional S/A',
          role: 'Analista de Sistemas / Desenvolvedor Full Stack Sênior',
          period: 'Abr/2012 – Mai/2024',
          location: 'São Paulo – SP',
          tasks: [
            'Desenvolvimento e manutenção de sistemas de alta criticidade para Saúde, Telemedicina e Faturamento Hospitalar (SOX / GMUD)',
            'Liderança técnica de squads: análise de requisitos, modelagem de dados, revisão de código e alinhamento com stakeholders',
            'Microservices com .NET Core (6 a 9), MassTransit, RabbitMQ, filas resilientes e desacopladas',
            'APIs REST com DDD, CQRS e Swagger/OpenAPI; autenticação OAuth 2.0 e JWT; integração SAP módulo FI para pagamento de médicos',
            'Sistema de agendamento on-line de consultas integrado a hospitais e consultórios',
            'Backend C# / ASP.NET (MVC e Web API) com Entity Framework Core e Dapper; SQL Server e Oracle 11g/19c',
            'Delphi 5/7/2007 (desktop e DataSnap) e Adobe Flex / Flash Builder 4 para sistema legado de prontuários',
            'Dashboards de observabilidade com Grafana e Zabbix; Python + MongoDB para métricas',
            'Uso intensivo de LLMs (GitHub Copilot, ChatGPT, Claude) e Engenharia de Prompt para acelerar entregas com código clean',
            'CI/CD com Azure DevOps e versionamento em GitHub/TFS',
          ],
        },
        {
          company: 'Voxel Informática',
          role: 'Analista Desenvolvedor Sênior – Delphi & .NET',
          period: 'Jan/2008 – Abr/2012',
          location: 'São Paulo – SP',
          tasks: [
            'Desenvolvimento em Delphi (5, 7, 2006) e C# / ASP.NET com SQL Server 2000/2005',
            'Adobe Flex / Flash Builder 4 para interfaces ricas',
            'Construção do portal "Viajar Barato" (compra coletiva): back-office e site público',
            'Relatórios com Quick Report e Crystal Report',
          ],
        },
        {
          company: 'Br01 – Propaganda e Publicidade',
          role: 'Analista Desenvolvedor Pleno/Sênior – .NET & Delphi',
          period: 'Ago/2007 – Jan/2008',
          location: 'São Paulo – SP',
          tasks: [
            'Sistemas web de alta visibilidade para Sony e OKI com C# ASP.NET e AJAX',
            'Modelagem de dados com ERWin; administração de Oracle 10g e SQL Server 2005',
            'Procedures, Triggers e manutenção de sistemas desktop em Delphi 2007',
          ],
        },
        {
          company: 'Prefeitura de Sorocaba',
          role: 'Analista de Sistemas e Desenvolvedor – Delphi',
          period: 'Abr/2007 – Ago/2007',
          location: 'Sorocaba – SP',
          tasks: [
            'Sistemas para secretarias de Educação, Guarda Municipal e HelpDesk',
            'Delphi (4 a 2006) + introdução a PHP e ASP.NET; Oracle, SQL Server e Firebird; Crystal Reports',
          ],
        },
        {
          company: 'Metalur Ltda',
          role: 'Analista Programador',
          period: 'Jan/2006 – Abr/2007',
          location: 'São Paulo – SP',
          tasks: [
            'Módulos de ERP: Produção, Faturamento, Financeiro e Estoque em Delphi, VB6 e C# (.NET)',
            'Manutenção de Oracle 8i e SQL Server com otimização de queries PL/SQL',
          ],
        },
      ],
    },
    skills: {
      comment: '// HABILIDADES',
      headingPrefix: 'Stack',
      headingHighlight: 'Técnica',
      description: 'Dashboard de competências técnicas com base em anos de experiência prática e projetos reais.',
      categories: [
        { title: 'BACKEND' },
        { title: 'ARQUITETURA' },
        { title: 'FRONTEND' },
        { title: 'MENSAGERIA & AUTH' },
        { title: 'BANCO DE DADOS' },
        { title: 'ORM / ACESSO A DADOS' },
        { title: 'CLOUD & DEVOPS' },
        { title: 'IA & LLMs' },
        { title: 'OBSERVABILIDADE' },
        { title: 'LEGADO' },
      ],
    },
    projects: {
      comment: '// PROJETOS',
      headingPrefix: 'Projetos em',
      headingHighlight: 'Destaque',
      description: 'Alguns dos projetos mais relevantes da minha carreira, desenvolvidos em ambientes de alta complexidade.',
      confidential: 'Confidencial',
      githubLink: 'Ver mais no GitHub →',
      items: [
        {
          title: 'Sistemas de Saúde & Telemedicina',
          description: 'Desenvolvimento e manutenção de sistemas de alta criticidade para Saúde, Telemedicina e Faturamento Hospitalar com conformidade SOX/GMUD. Agendamento on-line de consultas integrado a hospitais e consultórios.',
        },
        {
          title: 'APIs Financeiras – Banco Modal',
          description: 'APIs .NET Core com autenticação OAuth 2.0 / JWT. Integração com Azure (App Services, Key Vault, Storage) e deploy via CI/CD no Azure DevOps.',
        },
        {
          title: 'Microsserviços – MatriBank',
          description: 'Implementação de microsserviços com RabbitMQ/MassTransit, PostgreSQL e Redis para cache. Containerização com Docker e versionamento no GitHub/Bitbucket.',
        },
        {
          title: 'Cloud Solutions – Shock Tecnologia',
          description: 'Soluções em AWS (Lambda, S3, RDS) e GCP. Uso de Oracle Cloud para workloads legados Oracle. Pipelines de automação com Python.',
        },
        {
          title: 'Integração SAP & Faturamento Médico',
          description: 'Integração com SAP módulo FI para pagamento de médicos. Backend C# / ASP.NET com Entity Framework Core e Dapper. Dashboards de observabilidade com Grafana e Zabbix.',
        },
        {
          title: 'Portal Viajar Barato',
          description: 'Portal de compra coletiva com back-office administrativo e site público. Desenvolvido com Delphi, C# ASP.NET, Adobe Flex/Flash Builder 4 e SQL Server.',
        },
      ],
    },
    education: {
      comment: '// FORMAÇÃO',
      headingPrefix: 'Educação &',
      headingHighlight: 'Qualidades',
      graduationTitle: 'Sistemas de Informação',
      graduationSubtitle: 'Universidade de Sorocaba (UNISO) – 2007',
      continuousTitle: 'Educação Contínua',
      continuousSubtitle: 'Aprendizado constante e atualização',
      differentiatorsTitle: 'Diferenciais & Soft Skills',
      footerNote: 'Aberto a trabalho remoto / híbrido • Referências e portfólio disponíveis mediante solicitação',
      qualities: [
        { title: 'Alta Produtividade', desc: 'LLMs como copiloto de desenvolvimento diário — Engenharia de Prompt para código clean, testes e docs' },
        { title: 'Versatilidade', desc: 'Atua em stack completa: backend, frontend, banco, cloud, observabilidade e IA' },
        { title: 'Liderança Técnica', desc: 'Mentoria de times, code review, definição de arquitetura e boas práticas' },
        { title: 'Setor de Saúde', desc: '13+ anos em sistemas hospitalares, telemedicina e faturamento médico com conformidade SOX/GMUD' },
        { title: 'Comunicação', desc: 'Alinhamento com áreas de negócio, documentação técnica clara, metodologias ágeis (Scrum/Kanban)' },
      ],
      specializations: ['Arquitetura .NET', 'Microservices', 'DDD', 'Cloud', 'IA'],
    },
    contact: {
      comment: '// CONTATO',
      headingPrefix: 'Vamos',
      headingHighlight: 'Conversar?',
      description: 'Estou disponível para novos projetos, consultoria técnica ou oportunidades de liderança.',
      infoLabels: {
        email: 'E-mail',
        alternateEmail: 'E-mail alternativo',
        phone: 'Telefone',
        location: 'Localização',
      },
      actions: {
        email: 'Enviar E-mail',
        resume: 'Baixar Currículo PDF',
      },
    },
    footer: {
      madeWith: 'Feito com',
      by: 'por',
    },
  },
  en: {
    navbar: {
      links: [
        { href: '#about', label: 'About' },
        { href: '#experience', label: 'Experience' },
        { href: '#skills', label: 'Skills' },
        { href: '#projects', label: 'Projects' },
        { href: '#contact', label: 'Contact' },
      ],
      cta: 'Contact me',
      languageLabel: 'Language',
    },
    hero: {
      badge: 'Available for new projects',
      title: 'Senior Full Stack Developer',
      subtitle: 'Software Architecture • AI & Productivity with LLMs',
      experienceLine: '18+ years building high-performance systems',
      resumeButton: 'Download Resume',
      githubButton: 'GitHub',
    },
    about: {
      comment: '// ABOUT ME',
      headingPrefix: 'Experience that drives',
      headingHighlight: 'results',
      paragraphs: [
        'Senior Full Stack Developer with over 18 years of experience in highly complex enterprise systems, with strong expertise in the Healthcare & Telemedicine sector. Specialist in the .NET ecosystem (Framework through .NET 9), with solid command of modern architectures (Microservices, DDD, CQRS, Hexagonal) and messaging with RabbitMQ/MassTransit.',
        'Works with the leading LLMs in the market (ChatGPT, Claude, GitHub Copilot, Codex, Ollama) as high-productivity tools, applying Prompt Engineering to software development. Advanced authentication with OAuth 2.0, JWT, and Keycloak.',
        'Experience in Cloud (Azure, AWS, GCP, Oracle Cloud), CI/CD with Azure DevOps / GitHub / Bitbucket, observability with Grafana and Zabbix, and relational and NoSQL databases. My approach combines strategic business vision with technical excellence, always focusing on scalable solutions aligned with product goals.',
      ],
      highlights: [
        { title: '18+ Years', desc: 'Software development experience' },
        { title: 'Microservices', desc: 'DDD, CQRS, Hexagonal, Clean' },
        { title: 'Technical Leadership', desc: 'Mentoring and code review' },
        { title: 'Healthcare & Telemedicine', desc: '13+ years in the hospital sector' },
        { title: 'AI & LLMs', desc: 'Copilot, ChatGPT, Claude, Ollama' },
      ],
    },
    experience: {
      comment: '// CAREER PATH',
      headingPrefix: 'Professional',
      headingHighlight: 'Experience',
      description: 'A solid track record building mission-critical systems for leading companies in the market.',
      items: [
        {
          company: 'Shock Tecnologia Consultoria',
          role: 'Senior Full Stack Developer / Tech Lead',
          period: 'Jan/2026 – Present',
          location: 'Remoto',
          tasks: [
            'Provided services for clients such as MatriBank and Matri Precatórios using modern, microservices-oriented architecture',
            'MatriBank: .NET Core APIs with OAuth 2.0 and JWT; Azure App Services, Key Vault, and Storage; CI/CD in Azure DevOps',
            'Microservices with RabbitMQ and MassTransit; PostgreSQL and Redis for caching strategies; Docker; GitHub and Bitbucket',
            'Hands-on experience with banking processes and payment rails (PIX, TED, TEF, and Open Finance), including statement and reconciliation routines',
            'Integrations with financial providers such as Autbank and Celcoin',
            'Matri Precatórios: solutions on AWS (Lambda, S3, RDS) and GCP; Python automation pipelines',
            'Adoption of AI and LLMs (ChatGPT/Codex, Claude, Copilot, local Ollama) with prompt engineering for tests, refactoring, and documentation',
            'ALM and version control with GitHub, Bitbucket, Azure DevOps, and TFS; code review, GitFlow, and automated CI/CD pipelines',
          ],
        },
        {
          company: 'ITLean Consultoria',
          role: 'Senior Full Stack Developer',
          period: 'Jun/2024 – Jan/2026',
          location: 'Remoto',
          tasks: [
            'Provided services for clients such as GPA and Care Plus, modernizing systems and evolving critical platforms',
            'GPA: maintenance of pricing and labeling systems with WebForms (.NET Framework 4.7) and Oracle',
            'Built APIs in .NET 6/7/8 with CQRS, Clean Architecture, and SOLID, integrated with legacy mainframe systems',
            'Messaging and asynchronous processing with MassTransit and RabbitMQ for scalability and resilience',
            'Optimization of Oracle procedures and triggers with support from LLMs (Claude, GitHub Copilot, and Cursor), including agent creation',
            'Care Plus: migration from Delphi/WebForms legacy systems to .NET Core with microservices, CQRS, and messaging',
            'Development of APIs and interfaces with Angular and React for registration, onboarding, and beneficiary management flows',
            'Test automation and technical documentation generation with LLMs to accelerate delivery and improve quality',
          ],
        },
        {
          company: 'Amil Assistência Médica Internacional S/A',
          role: 'Systems Analyst / Senior Full Stack Developer',
          period: 'Apr/2012 – May/2024',
          location: 'São Paulo – SP',
          tasks: [
            'Development and maintenance of highly critical systems for Healthcare, Telemedicine, and Hospital Billing (SOX / GMUD)',
            'Technical leadership for squads: requirements analysis, data modeling, code review, and stakeholder alignment',
            'Microservices with .NET Core (6 to 9), MassTransit, RabbitMQ, and resilient decoupled messaging queues',
            'REST APIs with DDD, CQRS, and Swagger/OpenAPI; OAuth 2.0 and JWT authentication; SAP FI integration for physician payments',
            'Online appointment scheduling platform integrated with hospitals and medical offices',
            'Backend in C# / ASP.NET (MVC and Web API) with Entity Framework Core and Dapper; SQL Server and Oracle 11g/19c',
            'Delphi 5/7/2007 (desktop and DataSnap) and Adobe Flex / Flash Builder 4 for legacy medical records systems',
            'Observability dashboards with Grafana and Zabbix; Python + MongoDB for metrics',
            'Heavy use of LLMs (GitHub Copilot, ChatGPT, Claude) and Prompt Engineering to accelerate delivery with clean code',
            'CI/CD with Azure DevOps and version control on GitHub/TFS',
          ],
        },
        {
          company: 'Voxel Informática',
          role: 'Senior Developer Analyst – Delphi & .NET',
          period: 'Jan/2008 – Apr/2012',
          location: 'São Paulo – SP',
          tasks: [
            'Development in Delphi (5, 7, 2006) and C# / ASP.NET with SQL Server 2000/2005',
            'Adobe Flex / Flash Builder 4 for rich interfaces',
            'Built the "Viajar Barato" group-buying portal: back office and public website',
            'Reporting with Quick Report and Crystal Report',
          ],
        },
        {
          company: 'Br01 – Propaganda e Publicidade',
          role: 'Mid/Senior Developer Analyst – .NET & Delphi',
          period: 'Aug/2007 – Jan/2008',
          location: 'São Paulo – SP',
          tasks: [
            'High-visibility web systems for Sony and OKI with C# ASP.NET and AJAX',
            'Data modeling with ERWin; Oracle 10g and SQL Server 2005 administration',
            'Procedures, triggers, and maintenance of desktop systems in Delphi 2007',
          ],
        },
        {
          company: 'Prefeitura de Sorocaba',
          role: 'Systems Analyst and Developer – Delphi',
          period: 'Apr/2007 – Aug/2007',
          location: 'Sorocaba – SP',
          tasks: [
            'Systems for the Education department, Municipal Guard, and Help Desk',
            'Delphi (4 to 2006) + introduction to PHP and ASP.NET; Oracle, SQL Server, and Firebird; Crystal Reports',
          ],
        },
        {
          company: 'Metalur Ltda',
          role: 'Programmer Analyst',
          period: 'Jan/2006 – Apr/2007',
          location: 'São Paulo – SP',
          tasks: [
            'ERP modules: Production, Billing, Finance, and Inventory in Delphi, VB6, and C# (.NET)',
            'Maintenance of Oracle 8i and SQL Server with PL/SQL query optimization',
          ],
        },
      ],
    },
    skills: {
      comment: '// SKILLS',
      headingPrefix: 'Technical',
      headingHighlight: 'Stack',
      description: 'Technical skills dashboard based on years of hands-on experience and real-world projects.',
      categories: [
        { title: 'BACKEND' },
        { title: 'ARCHITECTURE' },
        { title: 'FRONTEND' },
        { title: 'MESSAGING & AUTH' },
        { title: 'DATABASES' },
        { title: 'ORM / DATA ACCESS' },
        { title: 'CLOUD & DEVOPS' },
        { title: 'AI & LLMs' },
        { title: 'OBSERVABILITY' },
        { title: 'LEGACY' },
      ],
    },
    projects: {
      comment: '// PROJECTS',
      headingPrefix: 'Featured',
      headingHighlight: 'Projects',
      description: 'Some of the most relevant projects in my career, built in highly complex environments.',
      confidential: 'Confidential',
      githubLink: 'See more on GitHub →',
      items: [
        {
          title: 'Healthcare & Telemedicine Systems',
          description: 'Development and maintenance of highly critical systems for Healthcare, Telemedicine, and Hospital Billing under SOX/GMUD compliance. Online appointment scheduling integrated with hospitals and clinics.',
        },
        {
          title: 'Financial APIs – Banco Modal',
          description: '.NET Core APIs with OAuth 2.0 / JWT authentication. Integration with Azure (App Services, Key Vault, Storage) and CI/CD deployment through Azure DevOps.',
        },
        {
          title: 'Microservices – MatriBank',
          description: 'Implementation of microservices with RabbitMQ/MassTransit, PostgreSQL, and Redis for caching. Containerized with Docker and versioned on GitHub/Bitbucket.',
        },
        {
          title: 'Cloud Solutions – Shock Tecnologia',
          description: 'Solutions on AWS (Lambda, S3, RDS) and GCP. Use of Oracle Cloud for legacy Oracle workloads. Python automation pipelines.',
        },
        {
          title: 'SAP Integration & Medical Billing',
          description: 'Integration with SAP FI module for physician payments. C# / ASP.NET backend with Entity Framework Core and Dapper. Observability dashboards with Grafana and Zabbix.',
        },
        {
          title: 'Viajar Barato Portal',
          description: 'Group-buying portal with administrative back office and public website. Built with Delphi, C# ASP.NET, Adobe Flex/Flash Builder 4, and SQL Server.',
        },
      ],
    },
    education: {
      comment: '// EDUCATION',
      headingPrefix: 'Education &',
      headingHighlight: 'Strengths',
      graduationTitle: 'Information Systems',
      graduationSubtitle: 'University of Sorocaba (UNISO) – 2007',
      continuousTitle: 'Continuous Education',
      continuousSubtitle: 'Continuous learning and upskilling',
      differentiatorsTitle: 'Differentiators & Soft Skills',
      footerNote: 'Open to remote / hybrid work • References and portfolio available upon request',
      qualities: [
        { title: 'High Productivity', desc: 'LLMs as daily development copilots — Prompt Engineering for clean code, tests, and docs' },
        { title: 'Versatility', desc: 'Works across the full stack: backend, frontend, databases, cloud, observability, and AI' },
        { title: 'Technical Leadership', desc: 'Team mentoring, code review, architecture decisions, and best practices' },
        { title: 'Healthcare Sector', desc: '13+ years in hospital systems, telemedicine, and medical billing with SOX/GMUD compliance' },
        { title: 'Communication', desc: 'Alignment with business areas, clear technical documentation, and agile practices (Scrum/Kanban)' },
      ],
      specializations: ['.NET Architecture', 'Microservices', 'DDD', 'Cloud', 'AI'],
    },
    contact: {
      comment: '// CONTACT',
      headingPrefix: 'Let\'s',
      headingHighlight: 'Talk?',
      description: 'I am available for new projects, technical consulting, or leadership opportunities.',
      infoLabels: {
        email: 'Email',
        alternateEmail: 'Alternative email',
        phone: 'Phone',
        location: 'Location',
      },
      actions: {
        email: 'Send Email',
        resume: 'Download Resume PDF',
      },
    },
    footer: {
      madeWith: 'Made with',
      by: 'by',
    },
  },
}
